name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: sudo apt-get install -y build-essential libncurses5-dev xvfb

    - name: Build project
      run: make

    - name: Start xvfb
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x16 &
    
    - name: Test project
      run: |
        export DISPLAY=:99
        ./xtask &
        sleep 5 # Run for 5 seconds to see output in action
        pkill xtask # Stop the program after the test

    - name: Clean up
      run: make clean
